export const menuSections = [
  {
    title: 'Featured',
    navLabel: 'Featured',
    items: [
      { name: 'Whole Chicken (Signature Charga Style)', price: '$22' },
      { name: 'Boneless Chicken Tikka Kabob Meal', price: '$15' },
      { name: 'Chicken Chili Momos (10)', price: '$14' },
    ],
  },
  {
    title: 'Specials',
    navLabel: 'Specials',
    items: [
      { name: 'House Burger w/ Fries & Drink', price: '$10' },
      { name: 'Crispy Chicken Sandwich w/ Fries & Drink', price: '$7' },
    ],
  },
  {
    title: 'Kabobs & Platters',
    navLabel: 'Kabobs',
    items: [
      { name: 'Boneless Chicken Tikka Kabob Meal', price: '$15' },
      { name: 'Chicken Tandoori Kabob Meal', price: '$13' },
      { name: 'Beef Seekh Kabob Meal', price: '$14' },
      { name: 'Ribeye Steak Kabob Meal', price: '$16' },
      { name: 'Lamb Tikka Kabob Meal', price: '$16' },
      { name: 'Salmon Tikka Kabob Meal', price: '$16' },
      { name: 'Paneer Tikka Kabob Meal', price: '$15' },
      { name: 'Jerk Kabob Meal', price: '$13' },
      { name: 'Kabob Combo (2)', price: '$21' },
      { name: 'Kabob Trio', price: '$35' },
      { name: 'Chicken Shawarma Platter', price: '$14' },
      { name: 'Chicken Biryani Bowl', price: '$12' },
      { name: 'Build Your Own Bowl', price: '$12' },
    ],
  },
  {
    title: 'Sandwiches & Wraps',
    navLabel: 'Sandwiches',
    items: [
      { name: 'Steak n Cheese', price: '$13' },
      { name: 'Chopped Cheese', price: '$13' },
      {
        name: 'Crispy Chicken Sandwich',
        price: '$8',
        description: 'Available regular or Nashville hot.',
      },
      { name: 'Grilled Chicken Sandwich', price: '$8' },
      { name: 'Chicken n Cheese', price: '$13' },
      { name: 'Lamb Gyro', price: '$10' },
      { name: 'Chicken Shawarma Wrap', price: '$10' },
      { name: 'Angus Beef Burger', price: '$10' },
      {
        name: 'Catfish Sandwich',
        price: '$8',
        description: 'Available fried or blackened.',
      },
      { name: 'Falafel Wrap', price: '$10' },
    ],
  },
  {
    title: 'Chicken and Wings',
    navLabel: 'Chicken & Wings',
    items: [
      {
        name: '1/4 Chicken (Signature Charga Style) w/ 2 Sides',
        price: '$11',
      },
      {
        name: '1/2 Chicken (Signature Charga Style) w/ 2 Sides',
        price: '$15',
      },
      {
        name: 'Whole Chicken (Signature Charga Style) w/ 4 Sides',
        price: '$32',
      },
      { name: '1/4 Chicken Only', price: '$6' },
      { name: '1/2 Chicken Only', price: '$12' },
      { name: 'Whole Chicken Only', price: '$22' },
      { name: '4 Whole Wings', price: '$8' },
      { name: '4 Whole Wings w/ 2 Sides', price: '$12' },
      { name: '10 Buffalo Wings', price: '$10' },
      { name: '20 Buffalo Wings', price: '$20' },
      { name: '30 Buffalo Wings', price: '$30' },
      { name: '50 Buffalo Wings', price: '$50' },
    ],
  },
  {
    title: 'Starters',
    navLabel: 'Starters',
    items: [
      { name: 'Samosa (1)', price: '$1.25' },
      { name: 'Samosa (5)', price: '$6' },
      { name: 'Samosa (10)', price: '$10' },
      { name: 'Samosa (15)', price: '$15' },
      { name: 'Samosa Family Pack (25)', price: '$25' },
      { name: 'Chicken Steam Momos (10)', price: '$12' },
      { name: 'Chicken Chili Momos (10)', price: '$14' },
    ],
  },
  {
    title: 'Extras',
    navLabel: 'Extras',
    items: [
      { name: 'Chicken Tikka Skewer', price: '$9' },
      { name: 'Chicken Tandoori Skewer', price: '$9' },
      { name: 'Beef Seekh Skewer', price: '$9' },
      { name: 'Ribeye Skewer', price: '$9' },
      { name: 'Lamb Tikka Skewer', price: '$9' },
      { name: 'Salmon Tikka Skewer', price: '$10' },
      { name: 'Tandoori Jerk Skewer', price: '$9' },
      { name: 'Falafels (6)', price: '$7' },
    ],
  },
  {
    title: 'Curry Menu',
    navLabel: 'Curry',
    items: [
      { name: 'Butter Chicken w/ Rice & Naan', price: '$20' },
      { name: 'Chicken Tikka Masala w/ Rice & Naan', price: '$20' },
      { name: 'Butter Paneer w/ Rice & Naan', price: '$20' },
      { name: 'Paneer Tikka Masala w/ Rice & Naan', price: '$20' },
      { name: 'Butter Salmon w/ Rice & Naan', price: '$23' },
      { name: 'Curry of the Day', price: '$11' },
    ],
  },
  {
    title: 'Sides',
    navLabel: 'Sides',
    note: 'All sides $5',
    compact: true,
    items: [
      { name: 'Fries (Sea Salt, Seasoned, Masala, Spicy Masala)' },
      { name: 'Biryani Rice', price: '$5' },
      { name: 'Lime Cilantro Rice', price: '$5' },
      { name: 'Mac n Cheese', price: '$5' },
      { name: 'Plantains', price: '$5' },
      { name: 'Side Salad', price: '$5' },
      { name: 'Tomato Cucumber Salad', price: '$5' },
      { name: 'Mixed Grilled Veggies', price: '$5' },
      { name: 'Chickpeas', price: '$5' },
      { name: 'Cooked Spinach', price: '$5' },
      { name: 'Pickled Beets' },
      { name: 'Pickled Onions' },
    ],
  },
  {
    title: 'Naan',
    items: [
      { name: 'Naan', price: '$2' },
      { name: 'Butter Naan', price: '$2.50' },
      { name: 'Garlic Butter Naan', price: '$2.50' },
    ],
  },
  {
    title: 'Drinks & Sauces',
    navLabel: 'Drinks',
    items: [
      { name: 'Mango Lassi', price: '$5' },
      { name: 'Bottled Water', price: '$1.50' },
      { name: 'Iced Tea', price: '$2' },
      { name: 'Soda', price: '$2' },
      { name: 'Garlic Sauce', price: '$0.50' },
      { name: 'Yellow Sauce', price: '$0.50' },
      { name: 'Mint Chutney', price: '$0.50' },
      { name: 'Green Sauce', price: '$0.50' },
      { name: 'Southwest Sauce', price: '$0.50' },
      { name: 'Peri Sauce', price: '$0.50' },
      { name: 'White Sauce', price: '$0.50' },
    ],
  },
]
